export const environment = {
  production: false,
  apiBaseUrl: '',
  blogUrl: '',
  servicesUrl: '',
  coursesUrl: '',
  ovhServerUrl: '',
  ovhTokenUrl: '',
  GITHUB_CLIENT_ID: '',
  STACK_OVERFLOW_CLIENT_ID: '',
  gitHubRedirectURL: '',
  stackOverflowRedirectURL: '',
  ovhAuthPassword: '',
  ovhAuthName: '',
};