export default {
    production: true,
    apiBaseUrl: 'API_BASE_URL',
    blogUrl: 'BLOG_URL',
    servicesUrl: 'SERVICES_URL',
    coursesUrl: 'COURSES_URL',
    ovhServerUrl: 'OVH_SERVER_URL',
    ovhTokenUrl: 'OVH_AUTH_URL',
    GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
    STACK_OVERFLOW_CLIENT_ID: 'STACK_OVERFLOW_CLIENT_ID',
    gitHubRedirectURL: 'GITHUB_REDIRECT_URL',
    stackOverflowRedirectURL: 'STACK_OVERFLOW_REDIRECT_URL',
    ovhAuthName: 'OVH_AUTH_NAME',
    courseRoutesActive: 'COURSE_ROUTES_ACTIVE',
    schoolApi: 'SCHOOL_API_BASE',
    vimeoToken: 'VIMEO_TOKEN',
    vimeoClientID: 'VIMEO_CLIENT_ID',
    vimeoClientSecret: 'VIMEO_CLIENT_SECRET',
    bannerText: 'BANNER_TEXT',
    bannerLink: 'BANNER_LINK',
    bannerActionBtn: 'BANNER_ACTION_BTN',
    bannerVisible: 'BANNER_VISIBLE'
}